### ISSUE TITLE
Running ScaCTM on one machine

### ISSUE THREAD

**Issue by rivulet-zhang** [cjf00000/ScaCTM#2]
Hi,

I am able to compile the code and my problem is I didn't have distributed clusters and only want to run it on one machine, I followed the manual and ran the following code:
ctm-train xxx.txt
It turned out that a bunch of "no such directory or folder" errors occurred. I looked at the ctm-train script and guess that the program tried to write files to a remote directory but I do not have such environment. Would you be able to provide some suggestions?

Thanks very much

**Comment by xunzheng** [comment]
Could you provide entire log stream? Just want to narrow down the scope.

**Comment by rivulet-zhang** [comment]
See below:
![error](https://cloud.githubusercontent.com/assets/10911507/6120668/e1170560-b0a6-11e4-898c-6099c58686d3.JPG)

I believe the program didn't really write files to my local machine. I then modified the code to create the directory:
![error1](https://cloud.githubusercontent.com/assets/10911507/6120689/09b89c54-b0a7-11e4-889e-acbb0902b607.JPG)

Then similar error occurred again:
![error2](https://cloud.githubusercontent.com/assets/10911507/6120700/1a5fc302-b0a7-11e4-9d57-c319e78cdc68.JPG)

**Comment by xunzheng** [comment]
Thanks. I'll take a look.
Quick questions: 
1) did you use MPI provided in third_party, or the default one? 
2) can you make sure `ssh localhost` works fine?

**Comment by rivulet-zhang** [comment]
I wasn't sure if it was MPI issue, however it works after I re-installed the third party module. 
Really appreciate your help!
